[package]
name= "send_message"
version="1.0.0"
authors=[]

[addresses]
send_message='0x88a758b195d35f7288934bede76c29b66185a18277eadee6423d757226ccbb54'
[dev-addresses]

[dependencies.AptosFrame]

git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
